openapi: 3.0.3
info:
  title: Espacio Workcafe Hours API
  description: Accepts a JSON object with text and returns the number of hours mentioned in the phrase "Espacio Workcafe X hora".
  version: 1.0.0

paths:
  /run-python:
    post:
      summary: Extract number of hours from Espacio Workcafe text
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                  description: Text containing the phrase "Espacio Workcafe X hora"
              required:
                - text
      responses:
        '200':
          description: Number of hours successfully extracted
          content:
            application/json:
              schema:
                type: object
                properties:
                  hours:
                    type: integer
                    description: Number of hours extracted from the text
        '400':
          description: Bad request (missing text field)
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '404':
          description: Pattern not found in the text
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

servers:
  - url: https://get-metrics.onrender.com
